ACuteArtInterface/ACuteArtInterface/ACuteArtInterface/ViewModels/ExhibitionViewModel.cs
using ACuteArtInterface.Helper;
using ACuteArtInterface.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using static ACuteArtInterface.Helper.Validations;

namespace ACuteArtInterface.ViewModels
{
    public class ExhibitionViewModel
    {
        [NotMappedAttribute]
        [MaxFileSize(100 * 1024)]
        [AllowedExtensions(new string[] { ".png", ".jpg", ".bmp", ".tif", ".tiff" })]
        [Display(Name = "Map Image URL"), DataType(DataType.Upload)]
        public IFormFile MainMapUrlFile { get; set; }

        [NotMappedAttribute]
        [MaxFileSize(100 * 1024)]
        [AllowedExtensions(new string[] { ".png", ".jpg", ".bmp", ".tif", ".tiff" })]
        [Display(Name = "Map Url"), DataType(DataType.Upload)]
        public IFormFile MapUrlFile { get; set; }

        [NotMappedAttribute]
        [MaxFileSize(100 * 1024)]
        [AllowedExtensions(new string[] { ".png", ".jpg", ".bmp", ".tif", ".tiff" })]
        [Display(Name = "Thumb Url (256x256)"), DataType(DataType.Upload)]
        public IFormFile ThumbUrlFile { get; set; }

        [NotMappedAttribute]
        [MaxFileSize(100 * 1024)]
        [AllowedExtensions(new string[] { ".png", ".jpg", ".bmp", ".tif", ".tiff" })]
        [Display(Name = "Icon Url (128x128)"), DataType(DataType.Upload)]
        public IFormFile IconUrlFile { get; set; }

        [NotMappedAttribute]
        [Display(Name = "Instruction URL"), DataType(DataType.Upload)]
        public IFormFile IntroUrlFile { get; set; }

        [NotMappedAttribute]
        [Display(Name = "How To"), DataType(DataType.Upload)]
        public IFormFile HowtoFile { get; set; }

        [NotMappedAttribute]
        public virtual List<UserModel> Users { get; set; }

        [NotMappedAttribute]
        public virtual List<ExhibitionArtworkModel> ExhibitionArtworks { get; set; }

        [NotMappedAttribute]
        public virtual ArtworkModel Artwork { get; set; }

        public virtual UserModel Owner { get; set; }

        public virtual ICollection<ExhibitionArtworkModel> Artworks { get; set; }

        [NotMappedAttribute]
        public string DescriptionEn { get; set; }

        [NotMappedAttribute]
        public IEnumerable<SelectListItem> drpExhibitionArtwork { get; set; }

        [NotMappedAttribute]
        [Display(Name = "Exhibitions")]
        public long[] ExhibitionArtworkIds { get; set; }
    }
}

ACuteArtInterface/ACuteArtInterface/ACuteArtInterface/Controllers/ExhibitionController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ACuteArtInterface.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;
using Microsoft.AspNetCore.Http;
using ACuteArtInterface.Helper;
using ACuteArtInterface.Services;
using Microsoft.Extensions.Configuration;
using ACuteArtInterface.Enums;
using X.PagedList;

namespace ACuteArtInterface.Controllers
{
    public class ExhibitionController : Controller
    {
        private readonly ApplicationContext _context;
        private readonly ILogger<ExhibitionController> _logger;

        public IConfiguration Configuration { get; }

        public ExhibitionController(ApplicationContext context, IConfiguration configuration, ILogger<ExhibitionController> logger)
        {
            _context = context;
            _logger = logger;
            Configuration = configuration;
        }

        #region Search

        /// <summary>
        /// 
        /// </summary>
        /// <param name="sortOrder"></param>
        /// <param name="currentFilter"></param>
        /// <param name="searchString"></param>
        /// <param name="pageNumber"></param>
        /// <param name="exhibitionId"></param>
        /// <returns></returns>
        public ActionResult SearchUser(string sortOrder, string currentFilter, string searchString, int? pageNumber, long? exhibitionId)
        {
            if (string.IsNullOrEmpty(sortOrder))
            {
                sortOrder = string.Empty;
            }

            ViewData["CurrentSort"] = sortOrder;
            ViewData["ExhibitionId"] = exhibitionId;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            var users = _context.AccUsers.Select(item => new UserModel
            {
                UserId = item.UserId,
                Name = item.Name,
                LastName = item.LastName,
                Email = item.Email
            }).ToList();

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                users = users.Where(p => (p.Name != null && p.Name.ToLower().Contains(searchString.ToLower())) || (p.Email != null && p.Email.ToLower().Contains(searchString.ToLower()))).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    users = users.OrderByDescending(p => p.Name).ToList();
                    break;
                default:
                    users = users.OrderBy(p => p.Name).ToList();
                    break;
            }

            int pageSize = 10;
            return PartialView("_SearchUser", users.ToPagedList(pageNumber ?? 1, pageSize));
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="sortOrder"></param>
        /// <param name="currentFilter"></param>
        /// <param name="searchString"></param>
        /// <param name="pageNumber"></param>
        /// <param name="exhibitionId"></param>
        /// <returns></returns>
        public ActionResult AddArtwork(string sortOrder, string currentFilter, string searchString, int? pageNumber, long? exhibitionId)
        {
            if (string.IsNullOrEmpty(sortOrder))
            {
                sortOrder = string.Empty;
            }

            ViewData["ExhibitionId"] = exhibitionId;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ArtworkExhibitionCheckModel model = new ArtworkExhibitionCheckModel();

            var artworks = _context.Artworks.Include(d => d.Artist).Select(item => new ArtworkModel
            {
                ArtistId = item.ArtistId,
                ArtworkId = item.ArtworkId,
                Active = item.Active,
                Name = item.Name,
                PrefabName = item.PrefabName,
                DescriptionEn = Helper.Helper.GetStringByLanguage(item.Description, 30),
                NameEn = Helper.Helper.GetStringByLanguage(item.Name, 0),
                ArtistNameEn = Helper.Helper.GetStringByLanguage(item.Artist.Name, 0),
            }).ToList();

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                artworks = artworks.Where(p => (p.Name != null && p.Name.ToLower().Contains(searchString.ToLower())) || (p.Description != null && p.Description.ToLower().Contains(searchString.ToLower()))).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    artworks = artworks.OrderByDescending(p => p.Name).ToList();
                    break;
                default:
                    artworks = artworks.OrderBy(p => p.Name).ToList();
                    break;
            }

            int pageSize = 10;
            return PartialView("_AddArtwork", artworks.ToPagedList(pageNumber ?? 1, pageSize));
        }

        #endregion Search

        #region Index and Details

        /// <summary>
        /// Returns all of the Exhibitions with pagination
        /// </summary>
        /// <param name="sortOrder">sort order by name, order, start date or end date</param>
        /// <param name="currentFilter">current sort filter</param>
        /// <param name="searchString">search keyword</param>
        /// <param name="pageNumber">page number for navigation</param>
        /// <returns></returns>
        [Authorize]
        public IActionResult Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["OrderSortParm"] = sortOrder == "Order" ? "order_desc" : "Order";
            ViewData["StartDateSortParm"] = sortOrder == "StartDate" ? "start_date_desc" : "StartDate";
            ViewData["EndDateSortParm"] = sortOrder == "EndDate" ? "end_date_desc" : "EndDate";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var exhibitions = _context.Exhibitions.Include(d => d.Owner).Select(item => new ExhibitionModel
            {
                Active = item.Active,
                Created = item.Created,
                Description = item.Description,
                EndDate = item.EndDate,
                ExhibitionId = item.ExhibitionId,
                GeoFenced = item.GeoFenced,
                Howto = item.Howto,
                Latitude = item.Latitude,
                Longitude = item.Longitude,
                MetaData = item.MetaData,
                OwnerId = item.OwnerId,
                Radius = item.Radius,
                ScanRadius = item.ScanRadius,
                ShowRadius = item.ShowRadius,
                SponsorImages = item.SponsorImages,
                SponsorName = item.SponsorName,
                StartDate = item.StartDate,
                Title = item.Title,
                UseGps = item.UseGps,
                ViewRadius = item.ViewRadius,
                IntroUrl = item.IntroUrl,
                MainMapUrl = item.MainMapUrl,
                MapUrl = item.MapUrl,
                IconUrl = item.IconUrl,
                ThumbUrl = item.ThumbUrl,
                Owner = _context.AccUsers.FirstOrDefault(user => user.UserId == item.OwnerId),
                DescriptionEn = Helper.Helper.GetStringByLanguage(item.Description, 30),
            }).ToList();

            //TODO: null check control

            if (!String.IsNullOrEmpty(searchString))
            {
                exhibitions = exhibitions.Where(s => s.Title.ToUpper().Contains(searchString.ToUpper()) ||
                                                    (s.Description != null && s.Description.ToUpper().Contains(searchString.ToUpper())) ||
                                                    (s.Owner != null && s.Owner.Name != null && s.Owner.Name.ToUpper().Contains(searchString.ToUpper()))).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    exhibitions = exhibitions.OrderByDescending(s => s.Title).ToList();
                    break;
                case "Order":
                    exhibitions = exhibitions.OrderBy(s => s.Order).ToList();
                    break;
                case "order_desc":
                    exhibitions = exhibitions.OrderByDescending(s => s.Order).ToList();
                    break;
                case "StartDate":
                    exhibitions = exhibitions.OrderBy(s => s.StartDate).ToList();
                    break;
                case "start_date_desc":
                    exhibitions = exhibitions.OrderByDescending(s => s.StartDate).ToList();
                    break;
                case "EndDate":
                    exhibitions = exhibitions.OrderBy(s => s.EndDate).ToList();
                    break;
                case "end_date_desc":
                    exhibitions = exhibitions.OrderByDescending(s => s.EndDate).ToList();
                    break;
                default:
                    exhibitions = exhibitions.OrderBy(s => s.Title).ToList();
                    break;

ACuteArtInterface/ACuteArtInterface/ACuteArtInterface/Views/Exhibition/Delete.cshtml
@model ACuteArtInterface.Models.ExhibitionModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Exhibition</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ACuteArtInterface/ACuteArtInterface/ACuteArtInterface/Views/Exhibition/_AddArtwork.cshtml
@*@using X.PagedList.Mvc.Core;
@model X.PagedList.IPagedList<ACuteArtInterface.Models.ArtworkModel>

<link href="@Url.Content("~/css/PagedList.css")" rel="stylesheet" type="text/css" />

<form asp-action="SaveArtworks" role="form" id="myForm">
    <div class="panel panel-default" id="filter">
        <table class="table">
            <thead>
                <tr>
                    <th></th>
                    <th><a asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Name</a></th>
                    <th>Prefab Name</th>
                    <th>Email</th>
                    <th><input type="hidden" name="ExhibitinId" asp-for="@ViewData["exhibitionId"]" value="@ViewData["ExhibitionId"]" /></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    @Html.HiddenFor(model => item.ArtworkId);
                    <tr>
                        <td><input asp-for="@item.Checked" type="checkbox" /></td>
                        <td>@item.Name</td>
                        <td>@item.PrefabName</td>
                        <td>@Html.ActionLink("Select Artwork", "Edit", "Exhibition", new { id = @ViewData["exhibitionId"], userId = item.ArtworkId }, new { @class = "btn btn-success btn-xs close", data_dismiss = "modal", data_toggle = "modal", data_target = "#myModal" })</td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
    <input type="submit" value="Save" id="btnSave" />
</form>
    <div id="myPager">
        <p>
            Find by Name/E-Mail: <input id="SearchString" name="SearchString" type="text" value="" />
            <input type="button" value="Search" id="btnSearch" /> | <input type="button" value="Clear Filter" id="btnClear" />
        </p>
        @Html.PagedListPager((X.PagedList.IPagedList)Model,
                  page => Url.Action(
                      "AddArtwork",
                      new
                      {
                          sortOrder = ViewBag.CurrentSort,
                          currentFilter = ViewBag.CurrentFilter,
                          searchString = ViewBag.SearchString,
                          pageNumber = page,
                          exhibitionId = @ViewData["exhibitionId"]
                      }
                  )
              )
    </div>

    <script>

    //Everytime we press delete in the table row
    $('.close').click(function (e) {
        e.preventDefault();
        $('#myModal').modal('hide');
        //var newUrl = window.location.origin + window.location.pathname + "?userId=" + e.userId;
        //window.location.href = newUrl;

        //location.reload();
    });

    window.addEventListener("popstate", function (e) {
        $.ajax({
            url: location.href,
            success: function (result) {
                $('#PreviewArtwork').html(result);
            }
        });
    });

    $('#myPager').on('click', 'a', function (e) {
        //prevent action link normal functionality
        e.preventDefault();
        if (this.href != null && this.href != "") {
            $.ajax({
                url: this.href,
                type: 'GET',
                cache: false,
                success: function (result) {
                    $('#PreviewArtwork').html(result);
                }
            });
            return false;
        }
    });

    $('#filter').on('click', 'a', function (e) {
        //prevent action link normal functionality
        e.preventDefault();
        if (this.href != null && this.href != "") {
            $.ajax({
                url: this.href,
                type: 'GET',
                data: { sortOrder: "NameSortParm", currentFilter: $("#SearchString").val(), searchString: $("#SearchString").val(), exhibitionId: @ViewData["ExhibitionId"]  },
                cache: false,
                success: function (result) {
                    $('#PreviewArtwork').html(result);
                }
            });
            return false;
        }
    });

    $(function () {
        $("#btnSearch").click(function () {
            search();
        });

        $("#btnClear").click(function () {
            clear();
        });

        $("#SearchString").keypress(function (e) {
            if (e.keyCode == 13) {
                search();
            }
        });

        $("#btnSelectUser").click(function () {
            selectUser();
        });

        function selectUser() {

            $.ajax({
                url: "/Exhibition/AddArtwork",
                data: { exhibitionId: $("#exhibitionId").val(), userId: $("#selectedUserItem").val() },
                success: function (result) {
                    $('#PreviewArtwork').html(result);
                }
            });
        }

        function search() {

            $.ajax({
                url: "/Exhibition/AddArtwork?searchString=" + $('#SearchString').val() + "&exhibitionId=" + @ViewData["ExhibitionId"],
                success: function (result) {
                    //ChangeUrl("index", "/Exhibition/SearchUser?searchString=" + $('#SearchString').val());
                    $('#PreviewArtwork').html(result);
                }
            });
        }

        function clear() {
            $.ajax({
                url: "/Exhibition/AddArtwork?exhibitionId=" + @ViewData["ExhibitionId"],
                success: function (result) {
                    $('#PreviewArtwork').html(result);
                }
            });
        }
    });
    </script>*@

ACuteArtInterface/ACuteArtInterface/ACuteArtInterface/Views/Exhibition/_SearchUser.cshtml
@*@using X.PagedList.Mvc.Core;
@model X.PagedList.IPagedList<ACuteArtInterface.Models.UserModel>

<link href="@Url.Content("~/css/PagedList.css")" rel="stylesheet" type="text/css" />

<div class="panel panel-default" id="filter">
    <table class="table">
        <thead>
            <tr>
                <th><a asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Name</a></th>
                <th>Last Name</th>
                <th>Email</th>
                <th><input type="hidden" name="ExhibitinId" asp-for="@ViewData["exhibitionId"]" value="@ViewData["ExhibitionId"]" /></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                @Html.HiddenFor(model => item.UserId);
                <tr>
                    <td>@item.Name</td>
                    <td>@item.LastName</td>
                    <td>@item.Email</td>

                    @{ var link = @ViewData["exhibitionId"] + "?userId=" + item.UserId;}
                    <td><a href=@link class="btn btn-success btn-xs close" data_dismiss="modal" data_toggle="modal" data_target="#myModal">Select User</a></td>
                    <td>@Html.ActionLink("Select User", "Edit", "Exhibition", new { id = @ViewData["exhibitionId"], userId = item.UserId }, new { @class = "btn btn-success btn-xs close", data_dismiss = "modal", data_toggle = "modal", data_target = "#myModal" })</td>
                </tr>
            }

        </tbody>
    </table>
</div>

<div id="myPager">
    <p>
        Find by Name/E-Mail: <input id="SearchString" name="SearchString" type="text" value="" />
        <input type="button" value="Search" id="btnSearch" /> | <input type="button" value="Clear Filter" id="btnClear" />
    </p>
    @Html.PagedListPager((X.PagedList.IPagedList)Model,
              page => Url.Action(
                  "SearchUser",
                  new
                  {
                      sortOrder = ViewBag.CurrentSort,
                      currentFilter = ViewBag.CurrentFilter,
                      searchString = ViewBag.SearchString,
                      pageNumber = page,
                      exhibitionId = @ViewData["exhibitionId"]
                  }
              )
          )
</div>

<script>

    //Everytime we press delete in the table row
    $('.close').click(function (e) {
        e.preventDefault();
        $('#myModal').modal('hide');
        //var newUrl = window.location.origin + window.location.pathname + "?userId=" + e.userId;
        //window.location.href = newUrl;

        //location.reload();
    });

    window.addEventListener("popstate", function (e) {
        $.ajax({
            url: location.href,
            success: function (result) {
                $('#Preview').html(result);
            }
        });
    });

    $('#myPager').on('click', 'a', function (e) {
        //prevent action link normal functionality
        e.preventDefault();
        if (this.href != null && this.href != "") {
            $.ajax({
                url: this.href,
                type: 'GET',
                cache: false,
                success: function (result) {
                    $('#Preview').html(result);
                }
            });
            return false;
        }
    });

    $('#filter').on('click', 'a', function (e) {
        //prevent action link normal functionality
        e.preventDefault();
        if (this.href != null && this.href != "") {
            $.ajax({
                url: this.href,
                type: 'GET',
                data: { sortOrder: "NameSortParm", currentFilter: $("#SearchString").val(), searchString: $("#SearchString").val(), exhibitionId: @ViewData["ExhibitionId"]  },
                cache: false,
                success: function (result) {
                    $('#Preview').html(result);
                }
            });
            return false;
        }
    });

    $(function () {
        $("#btnSearch").click(function () {
            search();
        });

        $("#btnClear").click(function () {
            clear();
        });

        $("#SearchString").keypress(function (e) {
            if (e.keyCode == 13) {
                search();
            }
        });

        $("#btnSelectUser").click(function () {
            selectUser();
        });

        function selectUser() {

            $.ajax({
                url: "/Exhibition/SearchUser",
                data: { exhibitionId: $("#exhibitionId").val(), userId: $("#selectedUserItem").val() },
                success: function (result) {
                    $('#Preview').html(result);
                }
            });
        }

        function search() {

            $.ajax({
                url: "/Exhibition/SearchUser?searchString=" + $('#SearchString').val() + "&exhibitionId=" + @ViewData["ExhibitionId"],
                success: function (result) {
                    //ChangeUrl("index", "/Exhibition/SearchUser?searchString=" + $('#SearchString').val());
                    $('#Preview').html(result);
                }
            });
        }

        function clear() {
            $.ajax({
                url: "/Exhibition/SearchUser?exhibitionId=" + @ViewData["ExhibitionId"],
                success: function (result) {
                    $('#Preview').html(result);
                }
            });
        }
    });
</script>*@