ACuteArtInterface/ACuteArtInterface/ACuteArtInterface/ViewModels/ExhibitionRoomViewModel.cs
using ACuteArtInterface.Helper;
using ACuteArtInterface.Models;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using static ACuteArtInterface.Helper.Validations;

namespace ACuteArtInterface.ViewModels
{
    public class ExhibitionRoomViewModel
    {
        [NotMappedAttribute]
        [MaxFileSize(100 * 1024)]
        [AllowedExtensions(new string[] { ".png", ".jpg", ".bmp", ".tif", ".tiff" })]
        [Display(Name = "On The Map Tab"), DataType(DataType.Upload)]
        public IFormFile MapIconUrlFile { get; set; }

        [NotMappedAttribute]
        [MaxFileSize(100 * 1024)]
        [AllowedExtensions(new string[] { ".png", ".jpg", ".bmp", ".tif", ".tiff" })]
        [Display(Name = "Map Url"), DataType(DataType.Upload)]
        public IFormFile MapUrlFile { get; set; }

        [NotMappedAttribute]
        [MaxFileSize(100 * 1024)]
        [AllowedExtensions(new string[] { ".png", ".jpg", ".bmp", ".tif", ".tiff" })]
        [Display(Name = "Thumb Url (256x256)"), DataType(DataType.Upload)]
        public IFormFile ThumbUrlFile { get; set; }

        [NotMappedAttribute]
        [MaxFileSize(100 * 1024)]
        [AllowedExtensions(new string[] { ".png", ".jpg", ".bmp", ".tif", ".tiff" })]
        [Display(Name = "Icon Url (128x128)"), DataType(DataType.Upload)]
        public IFormFile IconUrlFile { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public virtual ExhibitionModel Exhibition { get; set; }

        [NotMappedAttribute]
        public string TitleEn { get; set; }

        [NotMappedAttribute]
        public string DescriptionEn { get; set; }
    }
}

ACuteArtInterface/ACuteArtInterface/ACuteArtInterface/Controllers/ExhibitionRoomController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ACuteArtInterface.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using ACuteArtInterface.Helper;
using ACuteArtInterface.Services;
using ACuteArtInterface.Enums;

namespace ACuteArtInterface.Controllers
{
    public class ExhibitionRoomController : Controller
    {
        private readonly ApplicationContext _context;

        private readonly ILogger<ExhibitionRoomController> _logger;

        public IConfiguration Configuration { get; }

        public ExhibitionRoomController(ApplicationContext context, IConfiguration configuration, ILogger<ExhibitionRoomController> logger)
        {
            _context = context;
            _logger = logger;
            Configuration = configuration;
        }

        #region Index and Details

        /// <summary>
        /// Returns all of the ExhibitionRooms with pagination
        /// </summary>
        /// <param name="sortOrder">sort order by title, exhibition title or order</param>
        /// <param name="currentFilter">current sort filter</param>
        /// <param name="searchString">search keyword</param>
        /// <param name="pageNumber">page number for navigation</param>
        /// <returns></returns>
        [Authorize]
        public IActionResult Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["TitleSortParm"] = String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewData["ExhibitionTitleSortParm"] = sortOrder == "ExhibitionTitle" ? "exhibition_title_desc" : "ExhibitionTitle";
            ViewData["OrderSortParm"] = sortOrder == "Order" ? "order_desc" : "Order";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var exhibitionRooms = _context.ExhibitionRooms.Include(i => i.Exhibition).Select(item => new ExhibitionRoomModel
            {
                ExhibitionId = item.ExhibitionId,
                IconUrl = string.IsNullOrEmpty(item.IconUrl) ? "" : item.IconUrl,
                MapIconUrl = string.IsNullOrEmpty(item.MapIconUrl) ? "" : item.MapIconUrl,
                MapUrl = string.IsNullOrEmpty(item.MapUrl) ? "" : item.MapUrl,
                Order = item.Order,
                Active = item.Active,
                RoomId = item.RoomId,
                ScanRadius = item.ScanRadius,
                ShowOnMap = item.ShowOnMap,
                ThumbUrl = string.IsNullOrEmpty(item.ThumbUrl) ? "" : item.ThumbUrl,
                Title = string.IsNullOrEmpty(item.Title) ? "" : item.Title,
                Va = item.Va,
                VaGuid = string.IsNullOrEmpty(item.VaGuid) ? "" : item.VaGuid,
                Description = string.IsNullOrEmpty(item.Description) ? "" : item.Description,
                TitleEn = Helper.Helper.GetStringByLanguage(item.Title, 0),
                DescriptionEn = Helper.Helper.GetStringByLanguage(item.Description, 30),
                Exhibition = _context.Exhibitions.FirstOrDefault(user => user.ExhibitionId == item.ExhibitionId)
            }).ToList();

            if (!String.IsNullOrEmpty(searchString))
            {
                exhibitionRooms = exhibitionRooms.Where(s => s.Title.ToUpper().Contains(searchString.ToUpper())
                || (s.Description != null && s.Description.ToUpper().Contains(searchString.ToUpper())) ||
                   (s.Exhibition != null && s.Exhibition.Title != null && s.Exhibition.Title.ToUpper().Contains(searchString.ToUpper()))).ToList();
            }

            switch (sortOrder)
            {
                case "title_desc":
                    exhibitionRooms = exhibitionRooms.OrderByDescending(s => s.Title).ToList();
                    break;
                case "ExhibitionTitleSortParm":
                    exhibitionRooms = exhibitionRooms.OrderBy(s => s.Exhibition.Title).ToList();
                    break;
                case "exhibition_title_desc":
                    exhibitionRooms = exhibitionRooms.OrderByDescending(s => s.Exhibition.Title).ToList();
                    break;
                case "Order":
                    exhibitionRooms = exhibitionRooms.OrderBy(s => s.Order).ToList();
                    break;
                case "order_desc":
                    exhibitionRooms = exhibitionRooms.OrderByDescending(s => s.Order).ToList();
                    break;
                default:
                    exhibitionRooms = exhibitionRooms.OrderBy(s => s.Title).ToList();
                    break;
            }

            int pageSize = 10;
            return View(PaginatedList<ExhibitionRoomModel>.Create(exhibitionRooms, pageNumber ?? 1, pageSize));
        }

        /// <summary>
        /// GET: ExhibitionRoom/Details/5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<ActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // Commenting out original code to show how to use a raw SQL query.
            ExhibitionRoomModel exhibitionRooms = await _context.ExhibitionRooms.FindAsync(id);
            if (exhibitionRooms == null)
            {
                return NotFound();
            }

            //if (id != null)
            //{
            //    var exhibitionRooms = from d in _context.ExhibitionRooms
            //                          orderby d.Title
            //                          where d.ExhibitionId == exhibitionRooms.ExhibitionId
            //                          select d;

            //    ViewData["ExhibitionRooms"] = exhibitionRooms.ToList();
            //}

            //exhibitionRooms.Owner = _context.AccUsers.FirstOrDefault(user => user.UserId == exhibitionRooms.OwnerId);

            return View(exhibitionRooms);
        }

        #endregion Index and Details

        #region Create

        // GET: Exhibition/Create
        [RequestSizeLimit(737280000)]
        public ActionResult Create()
        {
            PopulateExhibitionsDropDownList(0);

            return View();
        }

        /// <summary>
        /// POST: ExhibitionRoom/Create
        /// </summary>
        /// <param name="exhibitionRoomModel"></param>
        /// <param name="MapIconUrlFile"></param>
        /// <param name="MapUrlFile"></param>
        /// <param name="ThumbUrlFile"></param>
        /// <param name="IconUrlFile"></param>
        /// <returns></returns>
        [HttpPost]
        [RequestSizeLimit(737280000)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Description,ExhibitionId,Order,Active,ScanRadius,ShowOnMap,VaGuid,Va,IconUrl,MapIconUrl,MapUrl,ThumbUrl,IconUrlFile,MapIconUrlFile,MapUrlFile,ThumbUrlFile")] ExhibitionRoomModel exhibitionRoomModel)
        {
            if (ModelState.IsValid)
            {
                exhibitionRoomModel.Active = true;

                #region Upload File to azure storage

                List<IFormFile> allFiles = new List<IFormFile> { exhibitionRoomModel.MapIconUrlFile, exhibitionRoomModel.MapUrlFile, exhibitionRoomModel.ThumbUrlFile, exhibitionRoomModel.IconUrlFile };

                foreach (IFormFile file in allFiles)
                {
                    if (file == null) { continue; }

                    //create file class to use uploading files
                    AzureBlobFile azureBlobFile = new AzureBlobFile(Enums.InterfaceFileTypes.Exhibition,
                                                                    file,
                                                                    await file.GetBytes(),
                                                                    exhibitionRoomModel.Title,
                                                                    string.Empty,
                                                                    Configuration.GetConnectionString("AccessKey"),
                                                                    Configuration.GetConnectionString("ContainerName"));

                    //create azure storace service
                    BlobStorageService objBlobService = new BlobStorageService(azureBlobFile.AccessKey, azureBlobFile.ContainerName);

                    //upload file to azure storage
                    string uploadedFileName = objBlobService.UploadFileToBlob(azureBlobFile);

                    //Set azure storage file nime into the model property
                    Helper.Helper.UpdateProperty(exhibitionRoomModel, azureBlobFile.PropertyName, uploadedFileName);
                }

                #endregion

                _context.Add(exhibitionRoomModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            PopulateExhibitionsDropDownList(0);

            return View(exhibitionRoomModel);
        }

        #endregion Create

        #region Edit

        /// <summary>
        /// GET: ExhibitionRoom/Edit/5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var exhibitionRoom = await _context.ExhibitionRooms

ACuteArtInterface/ACuteArtInterface/ACuteArtInterface/Views/ExhibitionRoom/Create.cshtml
@model ACuteArtInterface.Models.ExhibitionRoomModel

@{
    ViewBag.Title = "Create";
}

<h1>Exhibition Rooms</h1>
<h2>Create</h2>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" style="width: 1000px" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" rows="4" style="width: 1000px"> </textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExhibitionId" class="control-label"></label>
                <select asp-for="ExhibitionId" class="form-control" asp-items="ViewBag.ExhibitionID">
                    <option selected="selected">--- select Exhibition ---</option>
                </select>
                <span asp-validation-for="ExhibitionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Order" class="control-label"></label>
                <input asp-for="Order" class="form-control" />
                <span asp-validation-for="Order" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ScanRadius" class="control-label"></label>
                <input asp-for="ScanRadius" class="form-control" />
                <span asp-validation-for="ScanRadius" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShowOnMap" class="control-label"></label>
                <input asp-for="ShowOnMap" class="form-control" />
                <span asp-validation-for="ShowOnMap" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VaGuid" class="control-label"></label>
                <input asp-for="VaGuid" class="form-control" />
                <span asp-validation-for="VaGuid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MapIconUrlFile" class="control-label"></label>
                <input asp-for="MapIconUrlFile" class="form-control" name="MapIconUrlFile" id="MapIconUrlFile" type="file" accept="image/jpeg, image/png, image/bmp, image/tif, image/tiff" />
                <span asp-validation-for="MapIconUrlFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MapUrlFile" class="control-label"></label>
                <input asp-for="MapUrlFile" class="form-control" name="MapUrlFile" id="MapUrlFile" type="file" accept="image/jpeg, image/png, image/bmp, image/tif, image/tiff" />
                <span asp-validation-for="MapUrlFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ThumbUrlFile" class="control-label"></label>
                <input asp-for="ThumbUrlFile" class="form-control" name="ThumbUrlFile" id="ThumbUrlFile" type="file" accept="image/jpeg, image/png, image/bmp, image/tif, image/tiff" />
                <span asp-validation-for="ThumbUrlFile" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="IconUrlFile" class="control-label"></label>
                <input asp-for="IconUrlFile" class="form-control" name="IconUrlFile" id="IconUrlFile" type="file" accept="image/jpeg, image/png, image/bmp, image/tif, image/tiff" />
                <span asp-validation-for="IconUrlFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ACuteArtInterface/ACuteArtInterface/ACuteArtInterface/Views/ExhibitionRoom/Delete.cshtml
@model ACuteArtInterface.Models.ExhibitionRoomModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Exhibition Room</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ACuteArtInterface/ACuteArtInterface/ACuteArtInterface/Views/ExhibitionRoom/Index.cshtml
@model PaginatedList<ACuteArtInterface.Models.ExhibitionRoomModel>

@{ ViewData["Title"] = "Exhibition Room"; }

<link href="@Url.Content("~/css/modal.css")" rel="stylesheet" type="text/css" />
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

<h1>Exhibition Room</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find by Title/Description/Exhibition Title: <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Back to Full List</a>
        </p>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th><a asp-action="Index" asp-route-sortOrder="@ViewData["TitleSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Title</a></th>
            <th>
                Description
            </th>
            <th><a asp-action="Index" asp-route-sortOrder="@ViewData["ExhibitionTitleSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Exhibition Title</a></th>
            <th><a asp-action="Index" asp-route-sortOrder="@ViewData["OrderSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Order</a></th>
            <th>Scan Radius</th>
            <th>Show On Map</th>
            <th>Va Guid </th>
            <th>Va</th>
            <th>Active</th>
            <th>Map Icon Url</th>
            <th>Map Url</th>
            <th>Icon Url</th>
            <th>Thumb Url</th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @{ var thb = 0; var icn = 0; var map = 0; var mapi = 0;


            foreach (var item in Model)
            {
                var dataTargetMapIconUrl = "modelShowPictureMapIcon" + item.ExhibitionId + mapi;
                var dataTargetMapUrl = "modelShowPictureMap" + item.ExhibitionId + map;
                var dataTargetIconUrl = "modelShowPictureIcon" + item.ExhibitionId + icn;
                var dataTargetThumbUrl = "modelShowPictureThumb" + item.ExhibitionId + thb;


                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TitleEn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DescriptionEn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Exhibition.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Order)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ScanRadius)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ShowOnMap)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VaGuid)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Va)
                    </td>
                    <td>
                        @( item.Active ? "Yes" : "No" )
                    </td>
                    <td>
                        <!-- Modal -->
                        <div id=@dataTargetMapIconUrl class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title">@item.TitleEn Map Icon URL Picture</h4>
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div>
                                    <div class="modal-body">
                                        <img src="@item.MapIconUrl" />
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <button type="button" data-toggle="modal" data-target="#@dataTargetMapIconUrl">Show</button>
                    </td>
                    <td>
                        <!-- Modal -->
                        <div id=@dataTargetMapUrl class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title">@item.TitleEn Map URL Picture</h4>
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div>
                                    <div class="modal-body">
                                        <img src="@item.MapUrl" />
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <button type="button" data-toggle="modal" data-target="#@dataTargetMapUrl">Show</button>
                    </td>
                    <td>
                        <!-- Modal -->
                        <div id=@dataTargetIconUrl class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title">@item.TitleEn Icon URL Picture</h4>
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div>
                                    <div class="modal-body">
                                        <img src="@item.IconUrl" />
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <button type="button" data-toggle="modal" data-target="#@dataTargetIconUrl">Show</button>
                    </td>
                    <td>
                        <!-- Modal -->
                        <div id=@dataTargetThumbUrl class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title">@item.TitleEn Thumb URL Picture</h4>
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div>
                                    <div class="modal-body">
                                        <img src="@item.ThumbUrl" />
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <button type="button" data-toggle="modal" data-target="#@dataTargetThumbUrl">Show</button>
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "ExhibitionRoom", new { id = item.RoomId }) |
                        @Html.ActionLink("Details", "Details", "ExhibitionRoom", new { id = item.RoomId })
                    </td>
                </tr>

                thb++; icn++; map++; mapi++;
            } }
    </tbody>
</table>

@{ var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : ""; }

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>

<script>
    $('#myPager').on('click', 'a', function (e) {
        //prevent action link normal functionality
        e.preventDefault();
        if (this.href != null && this.href != "") {
            $.ajax({
                url: this.href,
                type: 'GET',
                cache: false,
                success: function (result) {
                    $('#Preview').html(result);
                }
            });
            return false;
        }
    });
</script>

ACuteArtInterface/ACuteArtInterface/ACuteArtInterface/Views/ExhibitionRoom/_CreateRoomItem.cshtml
@model ACuteArtInterface.Models.ExhibitionRoomModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" style="width: 1000px" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" rows="4" style="width: 1000px"> </textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExhibitionId" class="control-label"></label>
                <select asp-for="ExhibitionId" class="form-control" asp-items="ViewBag.ExhibitionID">
                    <option selected="selected">--- select Exhibition ---</option>
                </select>
                <span asp-validation-for="ExhibitionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Order" class="control-label"></label>
                <input asp-for="Order" class="form-control" />
                <span asp-validation-for="Order" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ScanRadius" class="control-label"></label>
                <input asp-for="ScanRadius" class="form-control" />
                <span asp-validation-for="ScanRadius" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShowOnMap" class="control-label"></label>
                <input asp-for="ShowOnMap" class="form-control" />
                <span asp-validation-for="ShowOnMap" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VaGuid" class="control-label"></label>
                <input asp-for="VaGuid" class="form-control" />
                <span asp-validation-for="VaGuid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MapIconUrl" class="control-label"></label>
                <input asp-for="MapIconUrl" class="form-control" name="MapIconUrlFile" type="file" accept="image/gif, image/jpeg, image/png" />
                <span asp-validation-for="MapIconUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MapUrl" class="control-label"></label>
                <input asp-for="MapUrl" class="form-control" name="MapUrlFile" type="file" accept="image/gif, image/jpeg, image/png" />
                <span asp-validation-for="MapUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ThumbUrl" class="control-label"></label>
                <input asp-for="ThumbUrl" class="form-control" name="ThumbUrlFile" type="file" accept="image/gif, image/jpeg, image/png" />
                <span asp-validation-for="ThumbUrl" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="IconUrl" class="control-label"></label>
                <input asp-for="IconUrl" class="form-control" name="IconUrlFile" type="file" accept="image/gif, image/jpeg, image/png" />
                <span asp-validation-for="IconUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>